### ISSUE TITLE
Added promise-based alternatives to the functional API

### ISSUE THREAD

**Issue by deliveryblueprints** [dhruvrajvanshi/ts-failable#1]
Hello,

The library supports the ability to `map` `mapError` and `flatMap` an `IFailable`. However currently, these functions are limited to non-async mappers. 

Would it be a good idea to add promise-based functions to support an async chain?

If so, could look into a MR. 

Thanks.

**Comment by dhruvrajvanshi** [comment]
This is a pretty good idea and I have not added them. I'll accept a PR but I'm closing this for now.
